### ISSUE TITLE
Bot should send my active tasks from jira to my chat

### ISSUE THREAD

**Issue by Maay** [dialogs/dialog-jira-bot#1]
We are the team of corporate messenger dialog. We have Java/Python/JavaScript Bot SDK to create bots in our messenger. Since it is new, we want to develop several bots with the help of the community for everyday use.

The documentation of our Java Bot SDK is here: https://docs.dlg.im/bots/java-bot.html

The documentation of our Python Bot SDK is here: https://dialogs.github.io/python-bot-sdk/ ⁣ ⁣ ⁣

The documentation of our JavaScript Bot SDK is here: https://dialogs.github.io/js-bot-sdk/

We'd prefer to use Python or JS SDK.

Our messenger has a test instance. Web client that you should use for the development is available here: https://grpc-test.transmit.im/

For web use this endpoint: https://grpc-test.transmit.im:8443
For bots use grpc endpoint: https://grpc-test.transmit.im:9443
Test accounts:
`alice` / `password`
After you've logged in you should write to `Security Bot` user (you can find him in the search field) and write command `/bot new bot_username bot_name` where `bot_username` is the username you can choose for your new bot and `bot_name` is his display name

We've open-sourced several bots that you can look up to for examples https://github.com/dialogs?utf8=%E2%9C%93&q=-bot&type=&language=

Please feel free to ask questions in our community https://dlg.im/@botsfordialog ⁣ ⁣

*Bot should send my active tasks from Jira to my chat*

1) Bot config should be managed from a text config file. In the config file, we specify data for integration with Jira. The author login in Jira and dialog is the same.
2) The user writes a bot in a personal or group chat message "Jarvis, what am I doing now?". The command should be configurable in config-file.
3) The bot sends a chat message with the name of each task in the "in progress" state assigned to the user. Each task is a separate row (line) in the message. Each line is formed as: `Time in progress - [PROJECT_CODE-TASK_ID](https://jira.domain.com/browse/PROJECT_CODE-TASK_ID) Title`. 

This is one of the features that this bot has. Look up other issues in this repo for other features. Each feature can be developed in separate bots (even in different languages but with the same name) using the same token. But, in case of a private chat with a bot, you have to add a check that peer id is equal to sender id in incoming SeqUpdate params. It’s needed to prevent the feature’s mutual influence. For example(Python):

```
def on_msg1(*params):
    if params[0].peer.id == params[0].sender_uid:  # this prevents false reactions 
        bot1.messaging.send_message(
            …
        )
```

For bounty to be verified, it’s necessary to create documentation for it.

**Comment by klisfer** [comment]
Hi. Can you explain what is 'Time In progress' in the output format?

**Comment by klisfer** [comment]
Have posted solution #1. Waiting for approval

**Comment by Drymonade** [comment]
@klisfer Hi there! Can you provide a link to your solution? I'm not sure which one of your repos is for that.

**Comment by klisfer** [comment]
@Drymonade Done. Kindly , check and review

**Comment by Drymonade** [comment]
@klisfer
We use server version of Jira, so we can't use API tokens. Can you please change auth method to login / password instead of login / token?

**Comment by klisfer** [comment]
@Drymonade  If you use password instead of token, it will work the same way

**Comment by Drymonade** [comment]
@klisfer That's OK, it works fine. But we need to get the only tasks which is assigned to user who asking the bot. Logins in dialog and jira both are the same.

**Comment by klisfer** [comment]
@Drymonade I have made the changes but I am unable to test it since the dialog messenger test instance is not working. Can you get that fixed so that I can test the code and push it.

**Comment by Drymonade** [comment]
@klisfer It's working now, you can test your solution.

**Comment by Drymonade** [comment]
@klisfer I've pulled changes and get this:
```
TypeError: Cannot read property 'emailAddress' of undefined
    at response.data.issues.map (/Users/skiba/dialog-jira-bot/app/index.js:56:35)
    at Array.map (<anonymous>)
    at axios.then.response (/Users/skiba/dialog-jira-bot/app/index.js:55:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by klisfer** [comment]
@Drymonade Fixed. Try it now

**Comment by Drymonade** [comment]
@klisfer Now I don't see any tasks :) But there are at least one task assigned to me in previous unfiltered list.

**Comment by Drymonade** [comment]
@klisfer It seems that you search for tasks that assigned to `JIRA_USERNAME`, but you should check the username of a user who asks bot for tasks.

**Comment by klisfer** [comment]
@Drymonade do you want the current user to be the "reporter" of the task or  the "creator" of the task. 
Those are the only two options in a jira task

**Comment by klisfer** [comment]
@Drymonade *Its "reporter" and "assignee". Reporter is set by default, whoever created the task is the reporter by default and assignee needs to be set separately. I have kept a check for the reporter of the task as in the person who created the task in JIRA.

**Comment by Drymonade** [comment]
@klisfer It would be OK to check `assignee` field only.

**Comment by klisfer** [comment]
@Drymonade . Done. The check is now on JIRA display name which is same as the dialog messenger username

**Comment by Drymonade** [comment]
@klisfer Can you check `assignee` of the task if it exists, not the `creator`?

**Comment by klisfer** [comment]
@Drymonade Done. It checks for asignee if it is not null

**Comment by Drymonade** [comment]
@klisfer Got this one:
```
TypeError: Cannot read property 'displayName' of null
    at response.data.issues.map.issue (/Users/skiba/dialog-jira-bot/app/index.js:68:39)
    at Array.map (<anonymous>)
    at axios.then.response (/Users/skiba/dialog-jira-bot/app/index.js:66:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by klisfer** [comment]
@Drymonade That happened because the tasks must have no asignee. How do you want me to handle the empty asignee. Should it return a message or do nothing?

**Comment by Drymonade** [comment]
@klisfer Just do nothing, we need only task with assignees.

**Comment by klisfer** [comment]
@Drymonade Done. It returns nothing if there is no asignee

**Comment by Drymonade** [comment]
@klisfer OK, well done) Thanks! Will merge it, you can go for bounty for this issue.

**Comment by Maay** [comment]
@klisfer please check the issue as solved on Bountysource!

**Comment by klisfer** [comment]
@Maay Done
